services:
  backend:
    build: .
    ports:
      - "443:443"
    volumes:
      - .:/app
    networks:
      - lan_postes
      - lan_serveurs
      - lan_admin

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db
    networks:
      - lan_admin

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo_db:27017/
    depends_on:
      - mongo_db
    networks:
      - lan_admin

  frontend:
    container_name: frontend
    build: ./dashboard
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - lan_admin


#Machines simulées sur lesquelles l'agent tourne
  poste1:
    container_name: poste1
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=https://backend:443
    volumes:
      - ./certs/ca.crt:/certs/ca.crt
      - ./certs/agent.crt:/certs/agent.crt
      - ./certs/agent.key:/certs/agent.key
    restart: always
    depends_on:
      - backend
    hostname: PC-25-87UP
    networks:
      - lan_postes

  poste2:
    container_name: poste2
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=https://backend:443
    volumes:
      - ./certs/ca.crt:/certs/ca.crt
      - ./certs/agent.crt:/certs/agent.crt
      - ./certs/agent.key:/certs/agent.key
    restart: always
    depends_on:
      - backend
    hostname: PC-26-8YUC
    networks:
      - lan_postes

  poste3:
    container_name: poste3
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=https://backend:443
    volumes:
      - ./certs/ca.crt:/certs/ca.crt #Certificat de CA public
      - ./certs/agent.crt:/certs/agent.crt #Certificat client signé par CA
      - ./certs/agent.key:/certs/agent.key #Clé privée de l'agent
    restart: always
    depends_on:
      - backend
    hostname: PC-24-98ML
    networks:
      - lan_postes

  serveur1:
    container_name: serveur-ftp
    build:
      context: ./agent/
      dockerfile: serveur-ftp/dockerfile
    environment:
      - BACKEND_URL=https://backend:443
    volumes:
      - ./certs/ca.crt:/certs/ca.crt
      - ./certs/agent.crt:/certs/agent.crt
      - ./certs/agent.key:/certs/agent.key
    restart: always
    depends_on:
      - backend
    hostname: SRV-FTP
    networks:
      - lan_serveurs

  serveur2:
    container_name: serveur-test
    build:
      context: ./agent/
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=https://backend:443
    volumes:
      - ./certs/ca.crt:/certs/ca.crt
      - ./certs/agent.crt:/certs/agent.crt
      - ./certs/agent.key:/certs/agent.key
    restart: always
    depends_on:
      - backend
    hostname: SRV-TEST
    networks:
      - lan_serveurs

  filtrage:
    container_name: filtrage
    build: ./filtrage
    cap_add:
      - NET_ADMIN

    #Utilise le "namespace" de l'hote, pas le sien. 
    #Permet que les règles IPtables s'appliquent au réseau hôte, et pas au conteneur lui même
    network_mode: host 
    
    restart: always
    depends_on:
      - backend

      

volumes:
  mongo_data:

networks:
  lan_postes:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

  lan_serveurs:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24

  lan_admin:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24