FROM python:3.11

WORKDIR /app

COPY agent.py .
COPY serveur-ftp/srv-script.sh .

RUN chmod +x ./srv-script.sh

RUN apt update && apt upgrade
RUN apt install vsftpd -y
RUN pip install psutil requests

CMD ["./srv-script.sh"] 