FROM python:3.11

RUN apt update -y && apt upgrade -y
RUN apt install vsftpd -y
RUN pip install psutil requests

WORKDIR /app

COPY agent.py .
COPY serveur-ftp/srv-script.sh .

RUN chmod +x ./srv-script.sh


CMD ["./srv-script.sh"] 