FROM python:latest

RUN apt update -y && apt upgrade -y
RUN apt install iputils-ping -y
RUN pip install --upgrade pip --no-cache-dir psutil requests

WORKDIR /app

COPY agent.py .

CMD ["python", "agent.py"]